// Writes supabase/setup.sql: the one-file setup pasted into the Supabase SQL
// editor on a fresh project (migrations in order, then the seed).
// Run: npm run db:setup-sql (after db:seed-sql).
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const dir = new URL("../supabase/", import.meta.url);
const migrations = readdirSync(new URL("migrations/", dir)).filter((f) => f.endsWith(".sql")).sort();

const header = `-- =====================================================================
-- Tailored Times: one-time database setup (schema + templates + prices)
-- Paste this whole file into Supabase → SQL Editor → New query → Run.
-- Run it ONCE on a fresh project. Running it again fails with
-- "already exists" errors; that is harmless and means it's already set up.
-- Generated by scripts/build-setup-sql.ts from migrations/ + seed.sql.
-- =====================================================================
`;

const footer = `
-- ---------------------------------------------------------------------
-- Make yourself an admin (do this after setup):
-- 1. Supabase → Authentication → Users → Add user → Create new user
--    (your email + a password, tick "Auto Confirm User").
-- 2. Replace the email below and run just these lines:
--
-- insert into public.admins (user_id, role)
-- select id, 'owner' from auth.users where email = 'you@example.com';
-- ---------------------------------------------------------------------

select 'Setup complete: ' || (select count(*) from public.templates) || ' templates loaded' as result;
`;

const parts = migrations.map((f) => `-- ---- migrations/${f}\n\n` + readFileSync(new URL(`migrations/${f}`, dir), "utf8"));
parts.push("-- ---- seed.sql\n\n" + readFileSync(new URL("seed.sql", dir), "utf8"));

writeFileSync(new URL("setup.sql", dir), [header, ...parts, footer].join("\n"));
console.log(`supabase/setup.sql written from ${migrations.length} migration(s) + seed`);
