// Writes supabase/seed.sql from src/data/templates.ts and DEFAULT_PRICING,
// so the database seed and the app's fallback data never drift apart.
// Run: npm run db:seed-sql
import { writeFileSync } from "node:fs";
import { TEMPLATES } from "../src/data/templates.ts";
import { DEFAULT_PRICING } from "../src/lib/pricing.ts";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const arr = (xs: string[]) => `array[${xs.map(q).join(", ")}]::text[]`;

const rows = TEMPLATES.map(
  (t, i) =>
    `  (${q(t.slug)}, ${q(t.legacySlug)}, ${q(t.name)}, ${q(t.category)}, ${q(t.blurb)}, ${i + 1}, ${arr(t.previewImages)})`,
).join(",\n");

const sql = `-- Generated by scripts/generate-seed.ts. Do not edit by hand.

insert into public.templates (slug, legacy_slug, name, category, blurb, sort_order, preview_images) values
${rows}
on conflict (slug) do update set
  legacy_slug = excluded.legacy_slug,
  name = excluded.name,
  category = excluded.category,
  blurb = excluded.blurb,
  sort_order = excluded.sort_order,
  preview_images = excluded.preview_images;

insert into public.pricing (id, config) values
  (1, ${q(JSON.stringify(DEFAULT_PRICING))}::jsonb)
on conflict (id) do nothing;
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`supabase/seed.sql written: ${TEMPLATES.length} templates + pricing`);
