-- =====================================================================
-- Tailored Times: one-time database setup (schema + templates + prices)
-- Paste this whole file into Supabase → SQL Editor → New query → Run.
-- Run it ONCE on a fresh project. Running it again fails with
-- "already exists" errors; that is harmless and means it's already set up.
-- Generated by scripts/build-setup-sql.ts from migrations/ + seed.sql.
-- =====================================================================

-- ---- migrations/0001_init.sql

-- Tailored Times: initial schema (21 Sep 2026).
-- Public visitors never touch tables directly: orders and contact messages
-- are inserted by server actions with the service role, which recalculate
-- the price first. Only users listed in `admins` can read or change data.

-- ---------------------------------------------------------------- admins

create table public.admins (
  user_id    uuid primary key references auth.users (id) on delete cascade,
  role       text not null default 'admin' check (role in ('owner', 'admin')),
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

-- ------------------------------------------------------------- templates

create table public.templates (
  id           uuid primary key default gen_random_uuid(),
  slug         text not null unique,
  legacy_slug  text unique,
  name         text not null,
  category     text not null,
  blurb        text not null default '',
  sort_order   int  not null default 0,
  active       boolean not null default true,
  preview_images text[] not null default '{}',
  -- Customisation fields for step 2 of the order (stories, names, photos…).
  -- Array of { key, label, type, required, help, options }.
  form_schema  jsonb not null default '[]'::jsonb,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- --------------------------------------------------------------- pricing

-- One row holding the whole PricingConfig (src/lib/pricing.ts) as JSON, so
-- admins can edit prices without a deploy.
create table public.pricing (
  id         int primary key default 1 check (id = 1),
  config     jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users (id)
);

-- ---------------------------------------------------------------- orders

create type public.order_status as enum
  ('ordered', 'created', 'printing', 'delivering', 'delivered', 'cancelled');

create sequence public.order_number_seq start 1;

create table public.orders (
  id             uuid primary key default gen_random_uuid(),
  reference      text not null unique
                   default 'TT-' || lpad(nextval('public.order_number_seq')::text, 6, '0'),
  template_id    uuid references public.templates (id) on delete set null,
  template_name  text not null,           -- kept even if the template is renamed or removed
  format         text not null check (format in ('Hard copy', 'Digital copy', 'Cover page')),
  size           text not null check (size in ('Tabloid', 'Broadsheet')),
  pages          int  not null check (pages > 0),
  copies         int  not null check (copies > 0),
  frames         boolean not null default false,
  designer       boolean not null default false,
  price          numeric(10, 2) not null,  -- calculated on the server
  currency       text not null default 'USD',
  status         public.order_status not null default 'ordered',
  payment_method text not null default 'cod',  -- cash on delivery only, for now
  customer_name  text not null,
  customer_phone text not null,
  customer_email text,
  delivery_address text not null,
  notes          text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index orders_status_idx  on public.orders (status);
create index orders_created_idx on public.orders (created_at desc);

create table public.order_answers (
  id        bigint generated always as identity primary key,
  order_id  uuid not null references public.orders (id) on delete cascade,
  field_key text not null,
  label     text not null,
  value     text not null default ''
);

create table public.order_files (
  id            bigint generated always as identity primary key,
  order_id      uuid not null references public.orders (id) on delete cascade,
  field_key     text,
  storage_path  text not null,
  original_name text,
  created_at    timestamptz not null default now()
);

create table public.order_events (
  id         bigint generated always as identity primary key,
  order_id   uuid not null references public.orders (id) on delete cascade,
  from_status public.order_status,
  to_status  public.order_status,
  note       text,
  created_by uuid references auth.users (id),
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------ contact messages

create table public.contact_messages (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  email      text not null,
  subject    text not null,
  message    text not null,
  handled    boolean not null default false,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------- updated_at trigger

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger templates_touch before update on public.templates
  for each row execute function public.touch_updated_at();
create trigger orders_touch before update on public.orders
  for each row execute function public.touch_updated_at();
create trigger pricing_touch before update on public.pricing
  for each row execute function public.touch_updated_at();

-- ------------------------------------------------------------------- RLS

alter table public.admins           enable row level security;
alter table public.templates        enable row level security;
alter table public.pricing          enable row level security;
alter table public.orders           enable row level security;
alter table public.order_answers    enable row level security;
alter table public.order_files      enable row level security;
alter table public.order_events     enable row level security;
alter table public.contact_messages enable row level security;

-- Anyone may read active templates and the price list (the calculator needs them).
create policy "public reads active templates" on public.templates
  for select using (active or public.is_admin());
create policy "public reads pricing" on public.pricing
  for select using (true);

-- Admins manage everything. No insert policy for anon: public writes go
-- through the service role in server actions.
create policy "admins manage templates" on public.templates
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage pricing" on public.pricing
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage orders" on public.orders
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage order answers" on public.order_answers
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage order files" on public.order_files
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage order events" on public.order_events
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage contact messages" on public.contact_messages
  for all using (public.is_admin()) with check (public.is_admin());
create policy "admins read admins" on public.admins
  for select using (public.is_admin());

-- --------------------------------------------------------------- storage

-- Private bucket for customer photos; admins view them through signed URLs.
insert into storage.buckets (id, name, public)
values ('order-uploads', 'order-uploads', false)
on conflict (id) do nothing;

create policy "admins read order uploads" on storage.objects
  for select using (bucket_id = 'order-uploads' and public.is_admin());

-- ---- seed.sql

-- Generated by scripts/generate-seed.ts. Do not edit by hand.

insert into public.templates (slug, legacy_slug, name, category, blurb, sort_order, preview_images) values
  ('birthday', 'birthday-template', 'Birthday 1', 'Birthdays', 'Turn any birthday into headline news with a fun, personalized newspaper-style template — perfect for parties, posts, or keepsakes.', 1, array['/templates/birthday/1.jpg', '/templates/birthday/2.jpg', '/templates/birthday/3.jpg', '/templates/birthday/4.jpg']::text[]),
  ('birthday-2', 'birthday-template-2', 'Birthday 2', 'Birthdays', 'A celebration of the lives we''ve lived and the moments that shaped us—every laugh, every tear, every wild detour. This is where memories rise, milestones shine, and another chapter begins with a bang.', 2, array['/templates/birthday-2/1.png', '/templates/birthday-2/2.png', '/templates/birthday-2/3.png', '/templates/birthday-2/4.png']::text[]),
  ('anniversary', 'anniversary-template', 'Anniversary', 'Anniversary', 'Celebrate love like it''s front-page news with a custom anniversary newspaper — a fun, personal way to relive the story of "us."', 3, array['/templates/anniversary/1.jpg', '/templates/anniversary/2.jpg', '/templates/anniversary/3.jpg', '/templates/anniversary/4.jpg']::text[]),
  ('retirement', 'retirement-template', 'Retirement', 'Retirements', 'Mark the end of an era with a personalized retirement newspaper — a memorable tribute to years of hard work, impact, and office legends.', 4, array['/templates/retirement/1.jpg', '/templates/retirement/2.jpg', '/templates/retirement/3.jpg']::text[]),
  ('mothers-fathers-day', 'mothers-day-template', 'Mother''s / Father''s Day', 'Mother''s & Father''s day', 'Celebrate Mom like the star she is with a custom newspaper — filled with love, laughs, and headline-worthy memories.', 5, array['/templates/mothers-fathers-day/1.jpg', '/templates/mothers-fathers-day/2.jpg', '/templates/mothers-fathers-day/3.jpg', '/templates/mothers-fathers-day/4.jpg']::text[]),
  ('summer-camp', 'summer-camp-template', 'Summer Camp', 'Summer camp souvenir', 'Capture campfire laughs and adventure-packed days with a custom summer camp newspaper — the perfect keepsake for unforgettable memories.', 6, array['/templates/summer-camp/1.jpg', '/templates/summer-camp/2.jpg', '/templates/summer-camp/3.jpg', '/templates/summer-camp/4.jpg']::text[]),
  ('menu', 'menu-template', 'Menu', 'Menu', 'Serve up your dishes in style with a custom newspaper-style menu — a unique way to add charm and character to any dining experience.', 7, array['/templates/menu/1.jpg', '/templates/menu/2.jpg', '/templates/menu/3.jpg', '/templates/menu/4.jpg']::text[]),
  ('christian-wedding', 'christan-wedding-template', 'Wedding 1 (Christian)', 'Wedding', 'A celebration of love, faith, and forever. This Christian wedding brings together two souls in holy matrimony, surrounded by blessings, vows, and cherished traditions—captured in timeless memories.', 8, array['/templates/christian-wedding/1.jpg', '/templates/christian-wedding/2.jpg', '/templates/christian-wedding/3.jpg', '/templates/christian-wedding/4.jpg']::text[]),
  ('muslim-wedding', 'muslim-wedding-template', 'Wedding 2 (Muslim)', 'Wedding', 'A heartfelt union under the light of tradition and prayer. This Nikah ceremony marks the beginning of a shared journey built on love, faith, and divine blessings—honoring sacred customs and celebrating new beginnings.', 9, array['/templates/muslim-wedding/1.jpg', '/templates/muslim-wedding/2.jpg', '/templates/muslim-wedding/3.jpg', '/templates/muslim-wedding/4.jpg']::text[]),
  ('basketball-tribute', 'basketball-tribute', 'Basketball Tribute', 'Sports tribute', 'A tribute to the court kings and queens who gave it their all—every bounce, every shot, every heartbeat. This is where hustle meets passion, where teamwork makes history, and where love for the game lives on.', 10, array['/templates/basketball-tribute/1.jpg', '/templates/basketball-tribute/2.jpg', '/templates/basketball-tribute/3.jpg', '/templates/basketball-tribute/4.jpg']::text[]),
  ('events', 'events-template', 'Events', 'Events', 'From milestones to memories in the making, this event is more than just a date on the calendar—it''s a celebration of life, laughter, and the people who make it unforgettable.', 11, array['/templates/events/1.jpg', '/templates/events/2.jpg', '/templates/events/3.jpg', '/templates/events/4.jpg']::text[]),
  ('baby-shower', 'baby-shower-template', 'Baby Shower', 'Baby showers', 'A day filled with love, laughter, and lullabies. This baby shower celebrates the joy of new beginnings, tiny kicks, and the big love growing every day. Here''s to the bundle of joy we can''t wait to meet!', 12, array['/templates/baby-shower/1.jpg', '/templates/baby-shower/2.jpg', '/templates/baby-shower/3.jpg', '/templates/baby-shower/4.jpg']::text[]),
  ('corporate', 'corporate-template', 'Corporate', 'Corporate', 'Highlight milestones, achievements, or company culture with a sleek, newspaper-style template — perfect for internal shoutouts or client-facing celebrations.', 13, array['/templates/corporate/1.jpg', '/templates/corporate/2.jpg', '/templates/corporate/3.jpg', '/templates/corporate/4.jpg']::text[]),
  ('fashion-magazine', 'fashion-magazine-template', 'Fashion Magazine', 'Fashion', 'A tribute to the icons who turned sidewalks into catwalks—every strut, every stare, every statement made. This is where style became identity, where confidence was couture, and where fashion wrote its own rules.', 14, array['/templates/fashion-magazine/1.png', '/templates/fashion-magazine/2.png', '/templates/fashion-magazine/3.png', '/templates/fashion-magazine/4.png']::text[]),
  ('promotion', 'promotion-template', 'Promotion', 'Promotions', 'A nod to the icons in the making—every capsule, every cut, every curve celebrated. This is not just a promo, it''s a personal style revolution.', 15, array['/templates/promotion/1.png', '/templates/promotion/2.png', '/templates/promotion/3.png', '/templates/promotion/4.png']::text[])
on conflict (slug) do update set
  legacy_slug = excluded.legacy_slug,
  name = excluded.name,
  category = excluded.category,
  blurb = excluded.blurb,
  sort_order = excluded.sort_order,
  preview_images = excluded.preview_images;

insert into public.pricing (id, config) values
  (1, '{"digitalPrice":20,"designerFee":20,"pageOptions":[1,4,8,12,16,20,24],"unitPrices":{"Tabloid":[{"maxQty":5,"unit":1.08},{"maxQty":10,"unit":1},{"maxQty":25,"unit":0.88},{"maxQty":50,"unit":0.79},{"maxQty":100,"unit":0.75},{"maxQty":250,"unit":0.7},{"maxQty":null,"unit":0.65}],"Broadsheet":[{"maxQty":5,"unit":3.25},{"maxQty":10,"unit":3.15},{"maxQty":25,"unit":3.05},{"maxQty":50,"unit":2.6},{"maxQty":100,"unit":2.85},{"maxQty":null,"unit":2.6}]},"framePrices":{"Tabloid":7.5,"Broadsheet":15.5},"boxPrices":{"Tabloid":1.4,"Broadsheet":3.3},"envelopePrices":{"Tabloid":1.4,"Broadsheet":2.7},"copiesPerFrameBox":4,"copiesPerBox":50,"envelopeMaxQty":13,"markup":1.11,"flatFee":5,"smallOrderMultipliers":{"8":3.38,"9":3.11,"10":3},"largeOrderBase":22,"largeOrderFrom":11,"largeOrderStepEvery":10,"largeOrderStepAdd":2}'::jsonb)
on conflict (id) do nothing;


-- ---------------------------------------------------------------------
-- Make yourself an admin (do this after setup):
-- 1. Supabase → Authentication → Users → Add user → Create new user
--    (your email + a password, tick "Auto Confirm User").
-- 2. Replace the email below and run just these lines:
--
-- insert into public.admins (user_id, role)
-- select id, 'owner' from auth.users where email = 'you@example.com';
-- ---------------------------------------------------------------------

select 'Setup complete: ' || (select count(*) from public.templates) || ' templates loaded' as result;
